export const ORDERS_ENDPOINTS = {
	POST_ORDERS_ORDERS: '/api/v1.0/orders/orders',
	GET_ORDERS_GETLASTORDERNUMBER_TYPE: '/api/v1.0/orders/getlastordernumber/{type}',
	PUT_ORDERS: '/api/v1.0/orders',
	GET_ORDERS_GETORDERIMAGE_ID: '/api/v1.0/orders/getorderimage/{id}',
	POST_ORDERS_ORDERIMAGE: '/api/v1.0/orders/orderimage',
	GET_ORDERS_ID: '/api/v1.0/orders/{id}',
	GET_ORDERS_ID_PREVIEW: '/api/v1.0/orders/{id}/preview',
	GET_ORDERS_ID_ORDER_LINES: '/api/v1.0/orders/{id}/order-lines',
	GET_ORDERS_ID_ORDER_LINES_PREVIEW: '/api/v1.0/orders/{id}/order-lines/preview',
	GET_ORDERS_ID_REMAININGSALESORDER: '/api/v1.0/orders/{id}/remainingsalesorder',
	GET_ORDERS_ID_REMAININGPURCHASEORDER: '/api/v1.0/orders/{id}/remainingpurchaseorder',
	DELETE_ORDERS_DELETESALESORDER: '/api/v1.0/orders/deletesalesorder',
	DELETE_ORDERS_DELETEPURCHASEORDER: '/api/v1.0/orders/deletepurchaseorder',
	PUT_ORDERS_UPDATE_STATUS_ISACTIVE: '/api/v1.0/orders/update-status/{isActive}',
	PUT_ORDERS_ORDERCLOSING: '/api/v1.0/orders/orderclosing',
	POST_ORDERS_ORDERINVOICES: '/api/v1.0/orders/orderinvoices',
	POST_ORDERS_ORDERSECOUNDRYINVOICES: '/api/v1.0/orders/ordersecoundryinvoices',
	POST_ORDERS_ORDERTRANSACTIONLISTREPORT: '/api/v1.0/orders/orderTransactionListReport',
	POST_ORDERS_ORDERTRANSACTIONLISTEXPORT: '/api/v1.0/orders/orderTransactionListExport',
} as const;
