export const PAYMENTPROVIDER_PAYMENTPROVIDERS_ENDPOINTS = {
	GET_PAYMENTPROVIDER_SETTING: '/api/v1.0/paymentProvider/setting',
	PUT_PAYMENTPROVIDER_SETTING: '/api/v1.0/paymentProvider/setting',
	GET_PAYMENTPROVIDER_PARAM_SETTING: '/api/v1.0/paymentProvider/param/setting',
	PUT_PAYMENTPROVIDER_PARAM_SETTING: '/api/v1.0/paymentProvider/param/setting',
	POST_PAYMENTPROVIDER_CREATE_PAYMENT_LINK: '/api/v1.0/paymentProvider/create-payment-link',
	POST_PAYMENTPROVIDER_PARAM_CREATE_PAYMENT_LINK: '/api/v1.0/paymentProvider/param/create-payment-link',
	POST_PAYMENTPROVIDER_PAYMENT_CALLBACK: '/api/v1.0/paymentProvider/payment-callback',
	POST_PAYMENTPROVIDER_PARAM_PAYMENT_CALLBACK: '/api/v1.0/paymentProvider/param/payment-callback',
	POST_PAYMENTPROVIDER_LIPAM_APPLICATION_FORM_WITH_EMAIL: '/api/v1.0/paymentProvider/lipam-application-form-with-email',
	POST_PAYMENTPROVIDER_LIPAM_QUICK_APPLICATION: '/api/v1.0/paymentProvider/lipam-quick-application',
	POST_PAYMENTPROVIDER_POS_APPLICATION: '/api/v1.0/paymentProvider/pos-application',
	GET_PAYMENTPROVIDER_POS_APPLICATION: '/api/v1.0/paymentProvider/pos-application',
	POST_PAYMENTPROVIDER_POS_PROVIDER_REQUEST: '/api/v1.0/paymentProvider/pos-provider-request',
	POST_PAYMENTPROVIDER_POS_APPLICATION_INFORMATION: '/api/v1.0/paymentProvider/pos-application-information',
	POST_PAYMENTPROVIDER_PAYNET_QUICK_APPLICATION: '/api/v1.0/paymentProvider/paynet-quick-application',
	GET_PAYMENTPROVIDER_PAYNET_REQUEST_LOGS_TAXNUMBER: '/api/v1.0/paymentProvider/paynet/request-logs/{taxnumber}',
	PUT_PAYMENTPROVIDER_PAYNET_REQUEST_LOGS: '/api/v1.0/paymentProvider/paynet/request-logs',
} as const;
