export const BANK_PAYMENTS_ENDPOINTS = {
  GET_PAYMENTS_BANK_BANKID: "/api/v1.0/payments/bank/{bankId}",
  DELETE_PAYMENTS_BANK_BANKID: "/api/v1.0/payments/bank/{bankId}",
  POST_PAYMENTS_GETBANKSTOTAL: "/api/v1.0/payments/getbankstotal",
  POST_PAYMENTS_BANKS: "/api/v1.0/payments/banks",
  GET_PAYMENTS_BANKBRANCH_BANKID: "/api/v1.0/payments/bankbranch/{bankId}",
  DELETE_PAYMENTS_BANKACCOUNT_BANKACCOUNTID: "/api/v1.0/payments/bankAccount/{bankAccountId}",
  PUT_PAYMENTS_BANK_BANK: "/api/v1.0/payments/bank/bank",
  GET_PAYMENTS_BANK_TRANSACTION_ID: "/api/v1.0/payments/bank/transaction/{id}",
  GET_PAYMENTS_BANK_TRANSACTION_ID_PREVIEW: "/api/v1.0/payments/bank/transaction/{id}/Preview",
  GET_PAYMENTS_BANK_INTEGRATION_ID_ACCOUNTS: "/api/v1.0/payments/bank/integration/{id}/accounts",
  GET_PAYMENTS_BANK_ALLINTEGRATEDACCOUNTS: "/api/v1.0/payments/bank/allintegratedaccounts",
  GET_PAYMENTS_ELOGOTESTASYNC: "/api/v1.0/payments/eLogoTestAsync",
  PUT_PAYMENTS_BANK_BANK_LIST: "/api/v1.0/payments/bank/bank/list",
  POST_PAYMENTS_BANK_INTEGRATION_TRANSACTIONS: "/api/v1.0/payments/bank/integration/transactions",
  GET_PAYMENTS_BANK_INTEGRATIONS: "/api/v1.0/payments/bank/integrations",
  GET_PAYMENTS_BANK_INTEGRATION_SETTINGS_ID: "/api/v1.0/payments/bank/integration-settings/{id}",
  PUT_PAYMENTS_BANK_INTEGRATION_SETTINGS: "/api/v1.0/payments/bank/integration-settings",
} as const;