export const UNIT_CODES = {
    C62: "Adet",
    KGM: "Kilogram",
    LTR: "Litre",
    GRM: "Gram",
    MTR: "Metre",
    MTK: "Metrekare",
    MTQ: "Metreküp",
    ML: "Mililitre",
    DMK: "Desimetre Kare",
    CMT: "Santimetre",
    CMQ: "Santimetre Küp",
    CMK: "Santimetre Kare",
    MLT: "Mililitre",
    MMQ: "Milimetre Küp",
    MM: "Milimetre",
    CTM: "Karat",
    BX: "Kutu",
    PF: "Palet",
    B32: "Kilogram/Metrekare",
    PR: "Çift",
    TNE: "Ton",
    D40: "Bin Litre",
    D30: "Brüt Kalori",
    GFI: "Gram Olarak İzotop",
    DAY: "Gün",
    MON: "Ay",
    ANN: "Yıl",
    HUR: "Saat",
    D61: "Dakika",
    D62: "Saniye",
    CM3: "Santimetre Küp",
    CM2: "Santimetre Kare",
    KG: "Kilogram",
    KM: "Kilometre",
    M3: "Metreküp",
    M2: "Metrekare",
    M: "Metre",
    G: "Gram",
    MG: "Miligram",
    L: "Litre",
    KG_M2: "Kilogram/Metrekare",
    BG: "Poşet",
    PA: "Paket",
    SET: "Set",
    NT: "Net Ton",
    GT: "Gross Ton",
    MND: "Kurutulmuş Net Ağırlık",
    D32: "Terawatt Saat",
    GWH: "Gigawatt Saat",
    MWH: "Megawatt Saat",
    KWH: "Kilowatt Saat",
    KWT: "Kilowatt",
    CEN: "Yüz Adet",
    MGM: "Miligram",
    CF: "Metreküp",
    LG: "Kütük",
    CL: "Kangal",
    SA: "Çuval",
    TY: "Silindirik Tank",
    PO: "Kese",
    SM: "Sac",
    RL: "Makara",
    RO: "Rulo",
    KUR: "Uranyum",
    VA: "Tekne",
    VX: "Vakuum Paket",
    PT: "Çömlek",
    RN: "Sıra",
    RD: "Sopa",
    KG_A: "Kilogram/Adet",
    PK: "Ambalaj",
    CT: "Tabaka",
    TU: "Küp",
    CN: "Konteyner",
    CU: "Küvet",
    TR: "Büyük Eşya Sandığı",
    SD: "Sabit Disk",
    FD: "Fotoğraf Dosyası",
    NE: "Paketlenmemiş veya Ambalajlanmamış",
    CR: "Sandık",
  };
  